version: "3.9"
services:
  web:
    build: ./JARS/JARS-API/
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Daingu_password123"
      ACCEPT_EULA: "Y"
