version: "3.9"
services:
  api:
    build:
      context: ./JARS/
      args:
        SSL_PASSWORD: ${SSL_PASSWORD}
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${SSL_PATH}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SSL_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      SA_PASSWORD: ${SA_PASSWORD}
  db:
    build: ./SQL/Setup/
    user: root
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - ./SQL/Data:/var/opt/mssql/data
