name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
    - name: Newman Action
      uses: matt-ball/newman-action@v1.0.4
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: ${{ secrets.POSTMAN_COLLECTION_UID }}
        environment: ${{ secrets.POSTMAN_ENVIRONMENT_UID }}
