name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
    - name: Newman Action
      uses: matt-ball/newman-action@v1.0.4
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: 19221303-96694d53-940f-4ae7-8d9f-4afc978498e1
        environment: ${{ secrets.POSTMAN_ENVIRONMENT_UID }}
